# Main landing page for 3nd.dev and www.3nd.dev
server {
    server_name 3nd.dev www.3nd.dev;

    root /var/www/3nd.dev/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    listen 80;
    listen [::]:80;

    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/3nd.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3nd.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

# Redirect all other 3nd.dev subdomains to dev.threenudedudes.com
server {
    server_name *.3nd.dev;

    return 301 https://dev.threenudedudes.com$request_uri;
}
