server {
    server_name lashes2.3nd.dev;
    root /var/www/lashes2.3nd.dev/public;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/lashes2.3nd.dev/public;
    }

    location / {
        proxy_pass http://127.0.0.1:3843;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/lashes2.3nd.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lashes2.3nd.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    server_name lashes2.3nd.dev;
    listen 80;
    listen [::]:80;
    return 301 https://$host$request_uri;
}